services:
  - type: web
    name: pipefy-document-ingestion-modular
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      # 🗄️ CONFIGURACIÓN SUPABASE (OBLIGATORIAS)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET_NAME
        value: documents
      
      # 🔗 CONFIGURACIÓN PIPEFY (OBLIGATORIAS)
      - key: PIPEFY_TOKEN
        sync: false
      - key: PIPEFY_WEBHOOK_SECRET
        sync: false
      
      # 🤖 COMUNICACIÓN CON CREWAI
      - key: CREWAI_SERVICE_URL
        value: https://pipefy-crewai-analysis-modular.onrender.com
      
      # 🆕 NUEVAS INTEGRACIONES SEGÚN PRD
      
      # 📱 TWILIO - Para notificaciones WhatsApp (OPCIONALES)
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        value: +17245586619
      
      # 🏭 CNPJá API - Para generación automática de Cartão CNPJ (OPCIONAL)
      - key: CNPJA_API_KEY
        sync: false 